import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillStar} from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'

import { useState } from 'react'

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Eunico Cornelius Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          {/* Navbar */}
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className=' text-xl font-burtons dark:text-white'>Eunico Cornelius</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className=' cursor-pointer text-xl dark:text-white'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>

          {/* First Section */}
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Eunico Cornelius</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer and Designer</h3>
            <p className='text-medium py-5 leading-8 text-gray-800 max-w-md md:max-w-xl mx-auto md:text-xl dark:text-gray-400'>
              Globally adapt professional developer providing services for programming and prototyping content needs. Contact me down below and let's get crackin!
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillYoutube/>
          </div>
          {/* 3D Profile Image */}
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden mb-10 md:h-96 md:w-96'>
            <Image src={deved} layout="fill" objectFit='cover'/>
          </div>
        </section>

        {/* Second Section */}
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Services I Offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
              Ever since I was a child, I have always dreamt of being a scientist. 
              But never have I thought, that I would be a <span className='text-teal-500'>Computer Scientist</span>. 
              Equipped with my bachelor's degree knowledge in Information Technology, I strive to create beatiful software applications in <span className='text-teal-500'>websites</span> and <span className='text-teal-500'>games</span>.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
              My expertise expands throughout the programming field with clean coding in mind. Creativity is my weapon of choice when creating software. <span className='text-teal-500'>ReactJS</span> allows me to bring to life beautiful responsive websites, which is then completed by MERN stack development. <span className='text-teal-500'>Unity</span> allows me to create immersive games using <span className='text-teal-500'>C#</span> scripting.
            </p>
          </div>
          {/* Skills Cards */}
          <div className='lg:flex gap-10'>
            {/* Skills #1: Design Card */}
            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-gray-700'>
              <Image src={design} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Designs</h3>
              <p className='py-2 dark:text-gray-300'>Creating elegant designs suited for your needs following core design theory.</p>
              <h4 className=' py-4 text-teal-600'>Design Tools I Use</h4>
              <p className=' text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
              <p className=' text-gray-800 py-1 dark:text-gray-400'>Figma</p>
              <p className=' text-gray-800 py-1 dark:text-gray-400'>Adobe XD</p>
            </div>
            {/* Skills #2: Programming Card */}
            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-gray-700'>
              <Image src={code} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Clean Programming</h3>
              <p className='py-2 dark:text-gray-300'>Algorithm understanding, clean programming accompanied by fast learning to achieve high softwaree standards.</p>
              <h4 className=' py-4 text-teal-600'>Programming Languages I Use</h4>
              <p className=' text-gray-800 py-1 dark:text-gray-400'>Javascript</p>
              <p className=' text-gray-800 py-1 dark:text-gray-400'>ReactJS</p>
              <p className=' text-gray-800 py-1 dark:text-gray-400'>Git</p>
              <p className=' text-gray-800 py-1 dark:text-gray-400'>C#</p>
            </div>
            {/* Skills #3: Team Card */}
            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-gray-700'>
              <Image src={consulting} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Team Player</h3>
              <p className='py-2 dark:text-gray-300'>Worked globally with lots of different culture and friendly faces. Not to mention, agile methodologies with a side of constructive criticism that gets the job done.</p>
              <h4 className=' py-4 text-teal-600'>Management Tools I Use</h4>
              <p className=' text-gray-800 py-1 dark:text-gray-400'>Jira</p>
              <p className=' text-gray-800 py-1 dark:text-gray-400'>SCRUM</p>
              <p className=' text-gray-800 py-1 dark:text-gray-400'>Kanban</p>
            </div>
          </div>
        </section>
        {/* Third Section */}
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
              I love exploring new experiences and methodologies. Some of my best work includes <span className='text-teal-500'>MERN</span> stack development, <span className='text-teal-500'>Flutter</span>, and more. Don't forget to leave a <span className=' text-yellow-500 font-bold'>star</span> if you liked it.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
